"""OpenAI-backed replies — an opt-in `AgentPolicy` that actually generates prose.

`policy.GroundedPolicy` is the default because it can never assert something ADARA did not
resolve. This is the other honest option the module docstring names: "a product that later wires a
real model swaps in its own AgentPolicy and the label changes with it." Wired in only when
OPENAI_API_KEY is set (see config.py) — freeform by request, meaning the transcript goes to the
model with none of ADARA's local-knowledge context injected. It can therefore answer things no
knowledge pack covers, and it can be wrong in the ordinary way a language model is wrong: `source`
on every reply says `openai:<model>`, never `grounded_template`, so a client or a log can always
tell which policy actually answered and weight its trust accordingly.
"""

from __future__ import annotations

import json
import logging
import urllib.error
import urllib.request

from .policy import Reply

logger = logging.getLogger(__name__)

DEFAULT_MODEL = 'gpt-4o-mini'
API_URL = 'https://api.openai.com/v1/chat/completions'
REQUEST_TIMEOUT_SECONDS = 20.0
MAX_HISTORY_TURNS = 6
MAX_REPLY_TOKENS = 200
"""A voice reply is spoken aloud; a 200-token cap keeps the wait and the playback both short."""

SYSTEM_PROMPT = (
    'You are ADARA, a helpful voice assistant. Reply briefly and naturally, the way you would '
    'speak out loud — a sentence or two, not a list or markdown. If the person is speaking a '
    'language other than English, answer in that same language.'
)


class OpenAIChatPolicy:
    """Replies generated by an OpenAI chat model. Freeform — no ADARA context is injected."""

    def __init__(self, *, api_key: str, model: str = DEFAULT_MODEL,
                 speech_available: bool = False,
                 speech_reason: str = 'no synthesis backend is wired') -> None:
        if not api_key:
            raise ValueError('OpenAIChatPolicy needs an api_key (set OPENAI_API_KEY)')
        self._api_key = api_key
        self._model = model
        self._source = f'openai:{model}'
        self._speech = {
            'available': speech_available,
            'reason': '' if speech_available else speech_reason,
        }

    def reply(self, meaning: dict, *, history: list | None = None) -> Reply:
        text = (meaning.get('transcript') or '').strip() if meaning else ''
        if not meaning or meaning.get('status') == 'error' or not text:
            return self._reply(
                'I did not catch that. Could you say it again?',
                act='ask_repeat', expects_answer=True,
            )

        messages = [{'role': 'system', 'content': SYSTEM_PROMPT}]
        messages.extend(_history_messages(history))
        messages.append({'role': 'user', 'content': text})

        try:
            answer = self._complete(messages)
        except Exception as error:  # noqa: BLE001 - a model outage must not fail the turn
            logger.warning('OpenAI completion failed: %s', error)
            return self._reply(
                'I understood you, but could not reach my language model just now.',
                act='report_unavailable',
                warnings=('The language model backend is unavailable.',),
            )

        if not answer:
            return self._reply(
                'I heard you, but had nothing to say back.', act='report_unavailable',
            )

        return self._reply(answer, act='acknowledge')

    def _complete(self, messages: list[dict]) -> str:
        body = json.dumps({
            'model': self._model,
            'messages': messages,
            'temperature': 0.5,
            'max_tokens': MAX_REPLY_TOKENS,
        }).encode('utf-8')
        request = urllib.request.Request(
            API_URL, data=body, method='POST',
            headers={
                'Authorization': f'Bearer {self._api_key}',
                'Content-Type': 'application/json',
            },
        )
        with urllib.request.urlopen(request, timeout=REQUEST_TIMEOUT_SECONDS) as response:
            payload = json.loads(response.read().decode('utf-8'))
        return payload['choices'][0]['message']['content'].strip()

    def _reply(self, text: str, **kwargs) -> Reply:
        return Reply(text=text, source=self._source, speech=dict(self._speech), **kwargs)


def _history_messages(history: list | None) -> list[dict]:
    """Prior turns as chat messages, oldest first, excluding the turn being answered right now.

    `history` is `session.turns`, and the turn this call is replying to has already been appended
    to it — including it here would show the model its own upcoming input as something already
    said, so the last entry is dropped before taking the window.
    """
    if not history or len(history) < 2:
        return []
    messages: list[dict] = []
    for turn in history[:-1][-MAX_HISTORY_TURNS:]:
        if turn.role == 'agent':
            content = (turn.reply or {}).get('text')
            role = 'assistant'
        else:
            content = turn.text
            role = 'user'
        if content:
            messages.append({'role': role, 'content': content})
    return messages
